plugins {
    id 'java-library'
}

dependencies {
    implementation project(':common')

    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.0'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.2'

    // TODO: Remove after migrating CurrencyapiService

    testImplementation "io.vertx:vertx-junit5:${vertxVersion}"
    testImplementation 'org.mockito:mockito-core:5.10.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.10.0'
}
