name: build-test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod u+x ./gradlew
      - name: Build with Gradle
        run: ./gradlew assemblyBot

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: majordomo-artifact
          path: bin/*.jar
      - name: folders
        run: ls -la

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up jdk 21
        uses: actions/setup-java@v4
        with:
          java-version:  21
          distribution:  'temurin'
          cache:  'gradle'
      - name: Grant execute permission for gradlew
        run: chmod u+x ./gradlew
      - name: Test with Gradle
        run: ./gradlew test